apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-token.fullname" . }}-token
  labels:
    {{- include "k8s-token.labels" . | nindent 4 }}

subjects:
- kind: ServiceAccount
  name: {{ include "k8s-token.fullname" . }}-token
roleRef:
  kind: Role
  name:  {{ include "k8s-token.fullname" . }}-token
  apiGroup: rbac.authorization.k8s.io