apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "k8s-token.fullname" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "k8s-token.fullname" . }}-token