// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "kubernetes_cluster" {
  type = object({
    authentication = object({
      cluster = object({
        certificate-authority-data = string
        server                     = string
      })
      user = object({
        token = string
      })
    })
    infrastructure = optional(object({
      arn             = optional(string)
      oidc_issuer_url = optional(string)
      ari             = optional(string)
      grn             = optional(string)
    }))
    specs = optional(any)
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "namespace" {
  type = string
}
variable "rules" {
  type = list(object({
    apiGroups = list(string)
    resources = list(string)
    verbs     = list(string)
  }))
}
